version: '3.8'

services:
  # PostgreSQL Database
  db_postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: trimly_db
      POSTGRES_USER: trimly_user
      POSTGRES_PASSWORD: trimly_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trimly_user -d trimly_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL Database
  db_mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: trimly_db
      MYSQL_USER: trimly_user
      MYSQL_PASSWORD: trimly_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://trimly_user:trimly_password@db_postgres:5432/trimly_db
      - MYSQL_URL=mysql://trimly_user:trimly_password@db_mysql:3306/trimly_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db_postgres:
        condition: service_healthy
      db_mysql:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # React Frontend
  frontend:
    build:
      context: ./trimly-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./trimly-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
  mysql_data:
  static_volume: